# Part 1: Theoretical Queltions

## Q1 What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow is a popular open-source machine learning library developed by Google. It provides various data structures to work with data efficiently in the context of deep learning and other machine learning tasks. Here are some of the key data structures used in TensorFlow:

1. **Tensors**: Tensors are multi-dimensional arrays that can represent data of different dimensions (scalars, vectors, matrices, etc.). They are the fundamental data structure in TensorFlow. You can think of them as the building blocks for constructing deep learning models.

    Example:
    ```python
    import tensorflow as tf
    tensor = tf.constant([1, 2, 3])
    ```
    
    
    

2. **Variables**: Variables are tensors that can be modified during training. They are typically used to store model parameters that need to be updated through gradient descent or other optimization algorithms.

    Example:
    ```python
    import tensorflow as tf
    variable = tf.Variable([1, 2, 3])
    ```



3. **Constants**: Constants are tensors with values that don't change during execution. They are often used for fixed values in your computations.

    Example:
    ```python
    import tensorflow as tf
    constant = tf.constant(42)
    ```



4. **Placeholders (deprecated in TensorFlow 2.x)**: In older versions of TensorFlow (1.x), placeholders were used to feed data into a TensorFlow computation graph. They have been replaced by `tf.data` and `tf.keras.utils.get_file()` functions in TensorFlow 2.x for more flexibility and performance.



5. **Sparse Tensors**: These are used to efficiently represent tensors with many default values. They are helpful when dealing with large, sparse data, such as text data or certain types of embeddings.

    Example:
    ```python
    import tensorflow as tf
    sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 1], [1, 2]], values=[1, 2], dense_shape=[3, 3])
    ```
    
    
    

6. **Ragged Tensors**: Ragged tensors represent data with varying lengths along one or more dimensions. They are useful for sequences of data with different lengths, like text sentences of varying lengths.

    Example:
    ```python
    import tensorflow as tf
    ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
    ```



7. **Datasets**: TensorFlow provides the `tf.data.Dataset` API to represent input data pipelines efficiently. Datasets are used for reading, preprocessing, and batching data during training.

    Example:
    ```python
    import tensorflow as tf
    dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size)
    ```

These are some of the fundamental data structures used in TensorFlow. Depending on your specific use case and the version of TensorFlow you are using, you may encounter additional data structures and APIs for more specialized tasks.

## Q2  How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

TensorFlow provides two fundamental data structures, constants and variables, each serving a different purpose in building and training machine learning models. Here's how they differ, along with examples:

**TensorFlow Constant:**

1. **Immutable**: A TensorFlow constant is a tensor with a fixed value that cannot be changed after creation. Once you define a constant, its value remains the same throughout the execution of your program.

2. **Typical Use**: Constants are typically used for fixed values that don't need to be updated during training. For example, you might use constants to represent hyperparameters or static values in your model.

3. **Example**:
   ```python
   import tensorflow as tf

   # Creating a TensorFlow constant
   constant_tensor = tf.constant([1, 2, 3])

   # Attempting to modify the constant will result in an error
   # constant_tensor.assign([4, 5, 6])  # This will raise an error
   ```

**TensorFlow Variable:**

1. **Mutable**: A TensorFlow variable is a tensor that can be modified during the execution of a TensorFlow program. Variables are typically used to store and update the learnable parameters of a machine learning model during training.

2. **Typical Use**: Variables are used to represent parameters that need to be updated through optimization algorithms like gradient descent. They are a fundamental part of training deep learning models.

3. **Example**:
   ```python
   import tensorflow as tf

   # Creating a TensorFlow variable
   initial_values = tf.constant([1, 2, 3])
   variable_tensor = tf.Variable(initial_values)

   # Modifying the variable's value
   variable_tensor.assign([4, 5, 6])

   # Accessing the updated value
   print(variable_tensor.numpy())  # This will print [4, 5, 6]
   ```

In summary, the main difference between TensorFlow constants and variables is their mutability. Constants are immutable, and their values remain fixed, while variables are mutable and are typically used for storing and updating parameters during training. Variables are essential for implementing machine learning algorithms as they allow the model to learn from data by adjusting their values iteratively through optimization techniques.

## Q3 Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

In TensorFlow, you can perform matrix addition, multiplication, and element-wise operations using tensors, which are multi-dimensional arrays. Here's a brief overview of how these operations work in TensorFlow:

1. **Matrix Addition:**

   Matrix addition is straightforward in TensorFlow. You can use the `tf.add()` function to add two tensors of the same shape element-wise. The tensors must have the same dimensions for addition to be valid.

   Example:
   ```python
   import tensorflow as tf

   # Define two matrices
   matrix1 = tf.constant([[1, 2], [3, 4]])
   matrix2 = tf.constant([[5, 6], [7, 8]])

   # Perform matrix addition
   result = tf.add(matrix1, matrix2)

   print(result.numpy())  # Output: [[6  8]
                         #          [10 12]]
   ```

2. **Matrix Multiplication:**

   Matrix multiplication can be performed using `tf.matmul()` or the `@` operator in TensorFlow. The key rule for matrix multiplication is that the number of columns in the first matrix must be equal to the number of rows in the second matrix.

   Example:
   ```python
   import tensorflow as tf

   # Define two matrices
   matrix1 = tf.constant([[1, 2], [3, 4]])
   matrix2 = tf.constant([[5, 6], [7, 8]])

   # Perform matrix multiplication
   result = tf.matmul(matrix1, matrix2)

   # Alternatively, you can use the @ operator
   # result = matrix1 @ matrix2

   print(result.numpy())  # Output: [[19 22]
                         #          [43 50]]
   ```

3. **Element-wise Operations:**

   Element-wise operations are operations that apply a function or operator to corresponding elements of two tensors of the same shape. Common element-wise operations include addition, subtraction, multiplication, division, and more.

   Example (element-wise multiplication):
   ```python
   import tensorflow as tf

   # Define two tensors of the same shape
   tensor1 = tf.constant([1, 2, 3])
   tensor2 = tf.constant([4, 5, 6])

   # Perform element-wise multiplication
   result = tf.multiply(tensor1, tensor2)

   print(result.numpy())  # Output: [ 4 10 18 ]
   ```

You can perform various other element-wise operations using TensorFlow's functions, such as `tf.add()`, `tf.subtract()`, `tf.multiply()`, and `tf.divide()`. These operations are commonly used in deep learning to apply activation functions, calculate gradients, and manipulate tensors in various ways during the construction and training of neural networks.

# Part 2 : Practical Implementation


## Task 1: Creating and Manipulating Matrices

### Q1 Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [7]:
import tensorflow as tf
import keras 
import warnings
warnings.filterwarnings('ignore')

In [9]:
matrix_A = tf.random.normal(shape=(3,3))
print(matrix_A)

tf.Tensor(
[[-0.9972431   0.07658315 -0.7657192 ]
 [ 0.16767868  0.30988738  1.5316368 ]
 [ 1.0279438   1.1410353  -0.16650687]], shape=(3, 3), dtype=float32)


### Q2 Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [14]:
matrix_B = tf.random.truncated_normal(shape=(4,4))
print(matrix_B)

tf.Tensor(
[[ 1.1095859  -1.2786194  -0.14233516 -0.78971905]
 [ 1.0293694   0.94857204  0.48043835  1.7049803 ]
 [ 0.42120314  0.30721283  0.5732003   0.18727495]
 [ 0.361877   -1.0728351  -0.76817745 -1.2357308 ]], shape=(4, 4), dtype=float32)


### Q3 Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [15]:
matrix_C = tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
print(matrix_C)

tf.Tensor(
[[3.7383046 2.617105 ]
 [2.270543  2.4716704]], shape=(2, 2), dtype=float32)


### Q3 Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

Here the dimension of Maxtrix A And Matrix B is not similar so we cant add it if we want to add to similar shapes matrixes then we can add using function "tf.add()"

matrix_D = tf.add(matrix_A,matrix_B)

### Q4 Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

matrix_E = tf.multiply(matrix_C,matrix_D)

## Task 2: Performing Additional Matrix Operation.

### Q1 Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [20]:
matrix_F = tf.random.uniform(shape=(3,3))
print(matrix_F)

tf.Tensor(
[[0.46485054 0.01639354 0.34105742]
 [0.7764001  0.32765722 0.05486441]
 [0.5416709  0.66921675 0.36944258]], shape=(3, 3), dtype=float32)


### Q2 Calculate the transpose of matrix F and store the result in matrix G.

In [21]:
matrix_G = tf.transpose(matrix_F)
print(matrix_G)

tf.Tensor(
[[0.46485054 0.7764001  0.5416709 ]
 [0.01639354 0.32765722 0.66921675]
 [0.34105742 0.05486441 0.36944258]], shape=(3, 3), dtype=float32)


### Q3 Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [22]:
matrix_H = tf.exp(matrix_F)

In [23]:
print(matrix_H)

tf.Tensor(
[[1.5917763 1.0165286 1.4064339]
 [2.1736333 1.3877132 1.0563973]
 [1.7188766 1.9527073 1.4469279]], shape=(3, 3), dtype=float32)


### Q4 Create a matrix I by concatenating matrix F and matrix G horizontally.

In [26]:
matrix_I = tf.concat([matrix_F,matrix_G],axis=1)
print(matrix_I)

tf.Tensor(
[[0.46485054 0.01639354 0.34105742 0.46485054 0.7764001  0.5416709 ]
 [0.7764001  0.32765722 0.05486441 0.01639354 0.32765722 0.66921675]
 [0.5416709  0.66921675 0.36944258 0.34105742 0.05486441 0.36944258]], shape=(3, 6), dtype=float32)


### Q5 Create a matrix J by concatenating matrix F and matrix H vertically.

In [28]:
matrix_J = tf.concat([matrix_F,matrix_H],axis=0)
print(matrix_J)

tf.Tensor(
[[0.46485054 0.01639354 0.34105742]
 [0.7764001  0.32765722 0.05486441]
 [0.5416709  0.66921675 0.36944258]
 [1.5917763  1.0165286  1.4064339 ]
 [2.1736333  1.3877132  1.0563973 ]
 [1.7188766  1.9527073  1.4469279 ]], shape=(6, 3), dtype=float32)
